### ISSUE TITLE
Last issue

### ISSUE THREAD

**Issue by weijia-cheng** [dazitzel/h-rider-haggard_when-the-world-shook#2]
- [ ] See [7.8.4](https://standardebooks.org/manual/1.7.0/7-high-level-structural-patterns#7.8.4). Your `<img>` tags need the `se:image.color-depth.black-on-transparent` semantic.

**Comment by dazitzel** [comment]
Semantics added and images converted per [7.8.4](https://standardebooks.org/manual/1.7.0/7-high-level-structural-patterns#7.8.4)
